### ISSUE TITLE
有谁跑通过这代码吗？

### ISSUE THREAD

**Issue by jx1100370217** [THUDM/P-tuning-v2#24]
如题。跑示例代码会报错：ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/1.15.1/metrics/super_glue/record_evaluation.py

**Comment by Xiao9905** [comment]
@jx1100370217 

你好，这是由于你的服务器无法连接github造成的。可以上网搜索修改hosts加速的方法来解决。

**Comment by Xiao9905** [comment]
@jx1100370217 Hi,

has your problem get resolved? Please feel free to reopen the issue if necessary.

**Comment by Jason7even** [comment]
我遇到了相同的错误，参考以下链接解决了，希望能帮到后来人。
https://blog.csdn.net/qq_15821487/article/details/121069536

**Comment by KissMyLady** [comment]
```sh
05/15/2023 17:19:03 - INFO - datasets.utils.file_utils - HEAD request to https://raw.githubusercontent.com/huggingface/datasets/2.3.2/metrics/super_glue/super_glue.py timed out, retrying... [1.0]
Traceback (most recent call last):
  File "run.py", line 130, in <module>
    trainer, predict_dataset = get_trainer(args)
  File "/home/mylady/code/ai/nlp/P-tuning-v2/tasks/superglue/get_trainer.py", line 30, in get_trainer
    dataset = SuperGlueDataset(tokenizer, data_args, training_args)
  File "/home/mylady/code/ai/nlp/P-tuning-v2/tasks/superglue/dataset.py", line 98, in __init__
    self.metric = load_metric("super_glue", data_args.dataset_name)
  File "/home/mylady/.virtualenvs/chatglm_tuning/lib/python3.8/site-packages/datasets/load.py", line 1335, in load_metric
    metric_module = metric_module_factory(
  File "/home/mylady/.virtualenvs/chatglm_tuning/lib/python3.8/site-packages/datasets/load.py", line 1277, in metric_module_factory
    raise e1 from None
  File "/home/mylady/.virtualenvs/chatglm_tuning/lib/python3.8/site-packages/datasets/load.py", line 1265, in metric_module_factory
    return GithubMetricModuleFactory(
  File "/home/mylady/.virtualenvs/chatglm_tuning/lib/python3.8/site-packages/datasets/load.py", line 537, in get_module
    local_path = self.download_loading_script(revision)
  File "/home/mylady/.virtualenvs/chatglm_tuning/lib/python3.8/site-packages/datasets/load.py", line 531, in download_loading_script
    return cached_path(file_path, download_config=download_config)
  File "/home/mylady/.virtualenvs/chatglm_tuning/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 185, in cached_path
    output_path = get_from_cache(
  File "/home/mylady/.virtualenvs/chatglm_tuning/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 533, in get_from_cache
    raise ConnectionError(f"Couldn't reach {url} ({repr(head_error)})")
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/2.3.2/metrics/super_glue/super_glue.py (ConnectionError(MaxRetryError("HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /huggingface/datasets/2.3.2/metrics/super_glue/super_glue.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef16c35070>: Failed to establish a new connection: [Errno 111] Connection refused'))")))
```

**Comment by Jason7even** [comment]
您好，我已经收到您的邮件，祝生活愉快。

**Comment by KissMyLady** [comment]
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/2.3.2/metrics/super_glue/super_glue.py (ConnectionError(MaxRetryError("HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /huggingface/datasets/2.3.2/metrics/super_glue/super_glue.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef16c35070>: Failed to establish a new connection: [Errno 111] Connection refused'))")))
