### ISSUE TITLE
AttributeError: No huggingface_hub attribute hf_api

### ISSUE THREAD

**Issue by loveJasmine** [THUDM/P-tuning-v2#54]
(gh_P-tuning-v2) ub2004@ub2004-B85M-A0:~/llm_dev/P-tuning-v2$ bash run_script/run_rte_roberta.sh
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    import datasets
  File "/home/ub2004/anaconda3/envs/gh_P-tuning-v2/lib/python3.8/site-packages/datasets/__init__.py", line 37, in <module>
    from .builder import ArrowBasedBuilder, BeamBasedBuilder, BuilderConfig, DatasetBuilder, GeneratorBasedBuilder
  File "/home/ub2004/anaconda3/envs/gh_P-tuning-v2/lib/python3.8/site-packages/datasets/builder.py", line 44, in <module>
    from .data_files import DataFilesDict, _sanitize_patterns
  File "/home/ub2004/anaconda3/envs/gh_P-tuning-v2/lib/python3.8/site-packages/datasets/data_files.py", line 120, in <module>
    dataset_info: huggingface_hub.hf_api.DatasetInfo,
  File "/home/ub2004/.local/lib/python3.8/site-packages/huggingface_hub/__init__.py", line 290, in __getattr__
    raise AttributeError(f"No {package_name} attribute {name}")
AttributeError: No huggingface_hub attribute hf_api
(gh_P-tuning-v2) ub2004@ub2004-B85M-A0:~/llm_dev/P-tuning-v2$

**Comment by cdliudc** [comment]
Am I encountering the same problem? How to solve it

**Comment by SeekPoint** [comment]
Attempting uninstall: datasets
    Found existing installation: datasets 2.11.0
    Uninstalling datasets-2.11.0:
      Successfully uninstalled datasets-2.11.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unstructured 0.5.13 requires argilla, which is not installed.
requests-oauthlib 1.3.1 requires oauthlib>=3.0.0, which is not installed.
gradio 3.23.0 requires httpx, which is not installed.
gradio-client 0.1.3 requires httpx, which is not installed.
altair 4.2.2 requires entrypoints, which is not installed.
matplotlib 3.7.1 requires numpy>=1.20, but you have numpy 1.19.2 which is incompatible.
icetk 0.0.7 requires protobuf<3.19, but you have protobuf 3.20.0 which is incompatible.
fairscale 0.4.13 requires numpy>=1.22.0, but you have numpy 1.19.2 which is incompatible.
Successfully installed datasets-2.3.2 dill-0.3.5.1 idna-3.4 multiprocess-0.70.13 numpy-1.24.3 pandas-1.4.4 requests-2.29.0 sacremoses-0.0.53 scipy-1.9.3 seqeval-1.2.2 tokenizers-0.10.3 tqdm-4.62.3 transformers-4.11.3
