### ISSUE TITLE
AttributeError: 'ExponentialTrainer' object has no attribute 'deepspeed'

### ISSUE THREAD

**Issue by Eskartur** [THUDM/P-tuning-v2#62]
Traceback (most recent call last):
  File "run.py", line 139, in <module>
    train(trainer, training_args.resume_from_checkpoint, last_checkpoint)
  File "run.py", line 26, in train
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/eskame0w/P-tuning-v2/training/trainer_exp.py", line 369, in train
    if self.deepspeed:
AttributeError: 'ExponentialTrainer' object has no attribute 'deepspeed'

**Comment by Eskartur** [comment]
I encountered this error when running CoNLL12 on BERT.
